import { FC, ReactNode } from 'react'
import {
  Arm,
  Astro,
  Bootstrap,
  C,
  Code,
  Codepen,
  Cpp,
  Csharp,
  Css,
  DotNet,
  Electron,
  External,
  Facebook,
  File,
  Folder,
  FreeCodeCamp,
  Gatsby,
  Git,
  GitHub,
  GraphQL,
  Html,
  Instagram,
  JavaScript,
  Link,
  LinkedIn,
  Markdown,
  Microchip,
  NestJS,
  NextJS,
  NodeJS,
  React,
  Redux,
  Sanity,
  Sass,
  StyledComponents,
  TailwindCSS,
  Terminal,
  Twitter,
  TypeScript,
  Upwork,
  X,
  YouTube
} from './Icons'

type Props = {
  name: string
}

export const Icon: FC<Props> = ({ name }) => {
  const iconComponents: Record<string, ReactNode> = {
    armcortexm: <Arm />,
    astro: <Astro />,
    bootstrap: <Bootstrap />,
    c: <C />,
    code: <Code />,
    codepen: <Codepen />,
    cpp: <Cpp />,
    csharp: <Csharp />,
    css: <Css />,
    dotnet: <DotNet />,
    dspic: <Microchip />,
    electron: <Electron />,
    external: <External />,
    facebook: <Facebook />,
    file: <File />,
    folder: <Folder />,
    freeCodeCamp: <FreeCodeCamp />,
    freertos: <Microchip />,
    gatsby: <Gatsby />,
    git: <Git />,
    github: <GitHub />,
    graphql: <GraphQL />,
    html: <Html />,
    instagram: <Instagram />,
    javascript: <JavaScript />,
    link: <Link />,
    linkedin: <LinkedIn />,
    markdown: <Markdown />,
    microchip: <Microchip />,
    nestjs: <NestJS />,
    nextjs: <NextJS />,
    nodejs: <NodeJS />,
    pic: <Microchip />,
    react: <React />,
    redux: <Redux />,
    sanity: <Sanity />,
    sass: <Sass />,
    styledcomponents: <StyledComponents />,
    tailwindcss: <TailwindCSS />,
    terminal: <Terminal />,
    twitter: <Twitter />,
    typescript: <TypeScript />,
    upwork: <Upwork />,
    x: <X />,
    youtube: <YouTube />
  }

  return iconComponents[name] || <External />
}
