import { Footer } from '@components/Footer'
import { Header } from '@components/Header'
import { type ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'Carlos Silva',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
